<a href="https://colab.research.google.com/github/ShiwenMahajuhck/Worksheet1/blob/main/Worksheet1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1.Initialize an empty array with size 2X2.

In [ ]:
import numpy as np

array= np.empty((2, 2))
print(array)



[[3.65676523e-315 0.00000000e+000]
 [5.04772904e-038 1.48286575e-071]]


2.Initialize an all one array with size 4X2.

In [ ]:
import numpy as np

array = np.ones((4, 2))
print(array)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


3.Return a new array of given shape and type, filled with fill value.{Hint: np.full}

In [ ]:
import numpy as np

array = np.full((3, 3), 7, dtype=int)
print(array)


[[7 7 7]
 [7 7 7]
 [7 7 7]]


4.Return a new array of zeros with same shape and type as a given array.{Hint: np.zeros like}

In [ ]:
import numpy as np

array = np.array([[1, 2, 3],
                [4, 5, 6]])

zeros_array = np.zeros_like(array)

print(zeros_array)


[[0 0 0]
 [0 0 0]]


5.Return a new array of ones with same shape and type as a given array.{Hint: np.ones like}

In [ ]:
import numpy as np

array = np.array([[3, 7],
                  [5, 9]])

ones_arr = np.ones_like(array)

print(ones_arr)


[[1 1]
 [1 1]]


6.For an existing list new_list = [1,2,3,4] convert to an numpy array.{Hint: np.array()}

In [ ]:
import numpy as np

new_list = [1, 2, 3, 4]

array = np.array(new_list)

print(array)


[1 2 3 4]


Problem 2
1. Create an array with values ranging from 10 to 49. {Hint:np.arrange()}.

In [ ]:
import numpy as np

array = np.arange(10, 50)

print(array)


[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Create a 3X3 matrix with values ranging from 0 to 8.
{Hint:look for np.reshape()}

In [ ]:
import numpy as np

array = np.arange(9).reshape(3, 3)

print(array)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


3. Create a 3X3 identity matrix.{Hint:np.eye()}

In [ ]:
import numpy as np

array = np.eye(3)

print(array)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


4. Create a random array of size 30 and find the mean of the array.
{Hint:check for np.random.random() and array.mean() function}

In [ ]:
import numpy as np

array = np.random.random(30)
mean_value = array.mean()

print(mean_value)


0.5371407654698018


5. Create a 10X10 array with random values and find the minimum and maximum values.

In [ ]:
import numpy as np

array = np.random.random((10, 10))
min_value = array.min()
max_value = array.max()

print(min_value)
print(max_value)


0.0024957769244232653
0.9639212083524935


6. Create a zero array of size 10 and replace 5th element with 1.

In [ ]:
import numpy as np

array = np.zeros(10)
array[4] = 1  # 5th element has index 4

print(array)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


7. Reverse an array arr = [1,2,0,0,4,0].

In [ ]:
import numpy as np

arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]

print(reversed_arr)


[0 4 0 0 2 1]


8. Create a 2d array with 1 on border and 0 inside.

In [ ]:
import numpy as np

array = np.ones((5, 5))
array[1:-1, 1:-1] = 0

print(array)


[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


9. Create a 8X8 matrix and fill it with a checkerboard pattern.

In [ ]:
import numpy as np

array = np.zeros((8, 8), dtype=int)
array[1::2, ::2] = 1
array[::2, 1::2] = 1

print(array)


[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


Problem 3
For the following arrays:
x = np.array([[1,2],[3,5]]) and y = np.array([[5,6],[7,8]]);
v = np.array([9,10]) and w = np.array([11,12]);
Complete all the task using numpy:
1. Add the two array.

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

sum_array = x + y

print(sum_array)


[[ 6  8]
 [10 13]]


2. Subtract the two array.

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])

diff_array = x - y

print(diff_array)


[[-4 -4]
 [-4 -3]]


3. Multiply the array with any integers of your choice.

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])

multiplied_array = x * 3  # multiplying by 3

print(multiplied_array)


[[ 3  6]
 [ 9 15]]


4. Find the square of each element of the array.

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])

squared_array = x ** 2

print(squared_array)


[[ 1  4]
 [ 9 25]]


5. Find the dot product between: v(and)w ; x(and)v ; x(and)y.

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

dot_v_w = np.dot(v, w)
dot_x_v = np.dot(x, v)
dot_x_y = np.dot(x, y)

print(dot_v_w)
print(dot_x_v)
print(dot_x_y)


219
[29 77]
[[19 22]
 [50 58]]


6. Concatenate x(and)y along row and Concatenate v(and)w along column.
{Hint:try np.concatenate() or np.vstack() functions.

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

concat_row = np.concatenate((x, y), axis=0)
concat_col = np.concatenate((v.reshape(-1,1), w.reshape(-1,1)), axis=1)

print(concat_row)
print(concat_col)



[[1 2]
 [3 5]
 [5 6]
 [7 8]]
[[ 9 11]
 [10 12]]


7. Concatenate x(and)v; if you get an error, observe and explain why did you get the error?

In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
v = np.array([9, 10])

concat_error = np.concatenate((x, v), axis=0)
print(concat_error)


ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

x is a 2D array of shape (2,2)

v is a 1D array of shape (2,)

np.concatenate requires that all arrays have the same number of dimensions. Here, a 2D array cannot be concatenated directly with a 1D array along rows or columns.

Problem 4
• For the following arrays:
A = np.array([[3,4],[7,8]]) and B = np.array([[5,3],[2,1]]);
Prove following with Numpy:
1. Prove A.A−1 = I.

In [ ]:
import numpy as np

A = np.array([[3, 4], [7, 8]])

A_inv = np.linalg.inv(A)
result = np.dot(A, A_inv)

print(result)


[[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]


2. Prove AB ̸= BA.

In [ ]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

AB = np.dot(A, B)
BA = np.dot(B, A)

print("A*B =\n", AB)
print("B*A =\n", BA)
print("Are A*B and B*A equal?", np.array_equal(AB, BA))


A*B =
 [[23 13]
 [51 29]]
B*A =
 [[36 44]
 [13 16]]
Are A*B and B*A equal? False


3. Prove (AB)

T = BTAT

In [ ]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

AB = np.dot(A, B)
AB_T = AB.T

B_T = B.T
A_T = A.T
BTA_T = np.dot(B_T, A_T)

print("Transpose of AB:\n", AB_T)
print("B.T * A.T:\n", BTA_T)
print("Are they equal?", np.array_equal(AB_T, BTA_T))


Transpose of AB:
 [[23 51]
 [13 29]]
B.T * A.T:
 [[23 51]
 [13 29]]
Are they equal? True


• Solve the following system of Linear equation using Inverse Methods.

2x − 3y + z = −1
x − y + 2z = −3
3x + y − z = 9

{Hint: First use Numpy array to represent the equation in Matrix form. Then Solve for: AX = B}

In [ ]:
import numpy as np

A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])

X = np.dot(np.linalg.inv(A), B)

print(X)


[ 2.  1. -2.]


• Now: solve the above equation using np.linalg.inv function.{Explore more about ”linalg” function
of Numpy}

In [ ]:
import numpy as np

A = np.array([[2, -3, 1],
              [1, -1, 2],
              [3, 1, -1]])

B = np.array([-1, -3, 9])

A_inv = np.linalg.inv(A)
X = A_inv.dot(B)

print(X)


[ 2.  1. -2.]
